language: python
python:
- 2.6
- 2.7
install:
- pip install coveralls
- pip install pyblish-endpoint
script:
- python run_testsuite.py
- pip install git+git://github.com/pyblish/pyblish-endpoint.git
after_success:
- coveralls
deploy:
  provider: pypi
  user: mottosso
  distributions: "sdist"
  password:
    secure: VhOE26X+tKYrT7Y9O6YLBDHnviV7LX+kIj+QQvKvs6NKVZm8R+mb/Z10MzLNgrnfwjUn2yY251zDva9S3cCiw3NcXcq4So85N6vDm+kG21GdV4NYW5NNa+eoAMFZlX5jfojq2QwE7fAqnE3aJ97uj8T97jGG1PiOFAZYAh1LSFs=
  on:
    tags: true
    all_branches: true
    python: 2.6
