language: python
python:
- 2.6
- 2.7
install:
- pip install coveralls
- pip install pyblish-endpoint
script:
- python run_testsuite.py
- pip install git+git://github.com/pyblish/pyblish-endpoint.git
after_success:
- coveralls
deploy:
  provider: pypi
  user: mottosso
  distributions: "sdist"
  password:
    secure: Sf/5Naw/bzdJTsKTPgDh6+Q4Lc5kE8BEGgJq03o6nuL6nj0W5m1fxfdCToZ5xEn4FaYBCS64GZ/wWO9DrqMq3D9d8v5NpF1jShQmip1wQa8b0o35n5cf2buSCNmR4ZY8+eRrMNK6492i6zmliDN4zvJX3PtkPJqP1leC0C01VlE=
  on:
    tags: true
    all_branches: true
