language: python
python:
- 2.6
- 2.7
install:
- pip install coveralls
- pip install pyblish-endpoint
script:
- python run_testsuite.py
- pip install git+git://github.com/pyblish/pyblish-endpoint.git
after_success:
- coveralls
deploy:
  provider: pypi
  user: mottosso
  distributions: "sdist"
  password:
    secure: iihNo1h6yRm+ZRg4hlO9Fhl4P+OEhQTKYkbwvC8y4rKTE+7qOUchP+dExw+mx3XXT/AcCMry94QE/GXUx76yV9IfKOiwkx5j7aeg1E5uaxxi76A6z59IlkWoYbYzVwWikeqHRIQzjHq4J+cy6TlZDHTooYnRs53ooibAJQenkDU=
  on:
    tags: true
    all_branches: true
